<?php
namespace AlegoApiWrapper\Constant;

class AlegoProduct
{
    // buy prepaid card
    const PREPAID_CARD_VIETTEL = 500;
    const PREPAID_CARD_MOBIFONE = 501;
    const PREPAID_CARD_VINAPHONE = 502;
    const PREPAID_CARD_SFONE = 503;
    const PREPAID_CARD_GMOBILE = 504;
    const PREPAID_CARD_VIETNAMEMOBILE = 505;

    // top up
    const TOPUP_PREPAID_VIETTEL = 600;
    const TOPUP_PREPAID_MOBIFONE = 601;
    const TOPUP_PREPAID_VINAPHONE = 602;
    const TOPUP_PREPAID_SFONE = 603;
    const TOPUP_PREPAID_GMOBILE = 604;
    const TOPUP_PREPAID_VIETNAMEMOBILE = 605;

    // top up after
    const TOPUP_POSTPAID_VIETTEL = 630;
    const TOPUP_POSTPAID_MOBIFONE = 631;
    const TOPUP_POSTPAID_VINAPHONE = 632;
    const TOPUP_POSTPAID_SFONE = 633;
    const TOPUP_POSTPAID_GMOBILE = 634;
    const TOPUP_POSTPAID_VIETNAMMOBILE = 635;

    // game card
    const GAME_PREPAID_CARD_V_COIN = 300;
    const GAME_PREPAID_CARD_GATE = 301;
    const GAME_PREPAID_CARD_SO_GARENA = 302;
    const GAME_PREPAID_CARD_ZING = 303;
    const GAME_PREPAID_CARD_ON_CASH = 305;
    const GAME_PREPAID_CARD_GO_COIN = 304;
    const GAME_PREPAID_CARD_MEGACARD = 306;
    const GAME_PREPAID_CARD_VCARD = 307;

} // end class
